#!/usr/bin/env python3
"""
Extract environment variable keys from render.yaml.
Outputs a structured list per service.
"""

import yaml
import sys
import os


def parse_render_yaml(file_path):
    with open(file_path, "r") as f:
        data = yaml.safe_load(f)

    services = data.get("services", [])
    result = {}

    for service in services:
        name = service.get("name")
        if not name:
            continue
        env_vars = []
        for env_var in service.get("envVars", []):
            key = env_var.get("key")
            if not key:
                continue
            info = {"key": key}
            if "value" in env_var:
                info["type"] = "value"
                info["value"] = env_var["value"]
            elif "generateValue" in env_var and env_var["generateValue"]:
                info["type"] = "generateValue"
            elif "fromService" in env_var:
                info["type"] = "fromService"
                info["service"] = env_var["fromService"].get("name")
            else:
                info["type"] = "unknown"
            # Note sync false
            if "sync" in env_var and not env_var["sync"]:
                info["sync"] = False
            env_vars.append(info)
        result[name] = env_vars
    return result


def main():
    file_path = sys.argv[1] if len(sys.argv) > 1 else "render.yaml"
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        sys.exit(1)

    services = parse_render_yaml(file_path)

    print("Environment Variables Configuration for Render Blueprint")
    print("=" * 60)
    for service_name, env_vars in services.items():
        print(f"\nService: {service_name}")
        print("  Environment Variables:")
        for env in env_vars:
            key = env["key"]
            typ = env["type"]
            if typ == "value":
                print(f"    - {key} = {env['value']} (value)")
            elif typ == "generateValue":
                print(f"    - {key} (auto-generated)")
            elif typ == "fromService":
                print(f"    - {key} (from service: {env['service']})")
            else:
                print(f"    - {key} (type: {typ})")
            if env.get("sync") is False:
                print(f"      ⚠️  sync: false - MUST set manually in Render dashboard")

    print("\n" + "=" * 60)
    print("Summary of variables that MUST be set manually in Render dashboard:")
    for service_name, env_vars in services.items():
        for env in env_vars:
            if env.get("sync") is False:
                print(f"  {service_name}.{env['key']}")

    print("\nNote: Variables with 'generateValue: true' are auto-generated by Render.")
    print("Variables with 'sync: false' must be set manually in Render dashboard.")


if __name__ == "__main__":
    main()
