#!/bin/bash
# Extract environment variable keys from render.yaml

set -e

RENDER_YAML="${1:-render.yaml}"
if [ ! -f "$RENDER_YAML" ]; then
    echo "Error: $RENDER_YAML not found"
    exit 1
fi

echo "Environment Variables from $RENDER_YAML"
echo "========================================="

# Use awk to parse YAML services and their envVars keys
# This is a simple parser, assumes YAML formatting as in our file
awk '
BEGIN {
    in_service = 0
    service_name = ""
    in_envVars = 0
    indent = 0
}
/^  - type: web/ {
    in_service = 1
    service_name = ""
    in_envVars = 0
}
/^    name:/ && in_service {
    gsub(/^    name: /, "")
    service_name = $0
}
/^    envVars:/ && in_service {
    in_envVars = 1
    indent = 4
    print "\nService: " service_name
    print "  Environment Variables:"
}
in_envVars && /^      - key:/ {
    gsub(/^      - key: /, "")
    if ($0 !~ /sync: false/ && $0 !~ /generateValue: true/) {
        print "    - " $0
    }
}
in_envVars && /^[^ ]/ && !/^    envVars:/ {
    in_envVars = 0
}
' "$RENDER_YAML"

echo ""
echo "Note: Variables with 'sync: false' must be set manually in Render dashboard."
echo "Variables with 'generateValue: true' are auto-generated by Render."